AppName = "MyApplication"
AppPort = "8080"
Environment = "local"

[ProjectsDb]
    Server = "localhost"
    Port = "5432"
    Database = "postgres"

[Logger]
   Level = ""

[Redis]
    Server = "localhost"
    Port = "6379"
    Database = 0
[Nats]
    Server = "localhost"
    Port = "4222"
[House]
    Server = "127.0.0.1"
    Port = "8124"
    Database = ""